import Head from "next/head";
import NavbarComponent from "../components/Navbar";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Letther - Pregunta en el eter</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* FULL WIDTH CONTAINER WITH BACKGROUND */}
      <div className="w-full h-full bg-gradient flex justify-center text-white">
        {/* APP CONTAINER 11/12 WIDTH  */}
        <div className="w-11/12 border-2 h-full flex flex-col">
          {/* NAVBAR */}
          <NavbarComponent />
        </div>
      </div>
    </div>
  );
};

export default Home;
