import AppContainer from "../components/AppContainer/AppContainer";
import Landing from "../components/Landing";

import Head from "next/head";
import { useRouter } from "next/router";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Letther - Pregunta en el eter</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppContainer>
        <Landing />
      </AppContainer>
    </div>
  );
};

export default Home;
